# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 309089aa857320e606403a00a8b7a39f03a89d4bb469f1b303c45d3685861f42869706c63da9a10bbadfd685c60f9c20c10e92e2a7527b2c6a5ea4e98e844436

test:
  secret_key_base: c8017c33dc7435ff54c227d3d1f8d0236f6d7e3375c7ec668217f9ac339e84aa6b29589ca3fc0c573ee6a9345a8479365f463d42688de234a87f51bd46d877d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
