# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f87dc5a9e01abca534c2b913ce887fc7cfcf3b7c12b4645b687c05519a839e3fd86736840a842a508c4b9f8dae433aff9691437b9661a015bc714a5d90f89ba8

test:
  secret_key_base: 79808252b64d29313aa8bf01a8dcf056791c9c688040b7bfbc3347b856cd5e7157c852f9ce6371f4de28f653d58c6123642e57d20c69dbd350dbcab9e62b7797

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
