# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 638ec5d75977d38b96e2265114ec69622e26731c7b2056627eaa725a1a7a2c3a3c172abd09bc18f1495969635bf79e0885322531cfc479a841c0fc4469c2e401

test:
  secret_key_base: 654c337ab0935381faeeda8e3e125b0a50c7172f53740cfbbfb123ead45e64da10dbe5a4617d0de979d2c384c13da4b9b14b06fbdd8e19e07944eec981b4c491

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
